// <auto-generated />
using System;
using KrishiBazaarProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrishiBazaarProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250308091330_addedBoolIsReviewedToOrders")]
    partial class addedBoolIsReviewedToOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KrishiBazaarProject.Models.Admins", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryID"));

                    b.Property<int?>("CurrentLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("DeliveryID");

                    b.HasIndex("CurrentLocationID");

                    b.HasIndex("OrderID")
                        .IsUnique()
                        .HasFilter("[OrderID] IS NOT NULL");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Location", b =>
                {
                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoadDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upazila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostalCode");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Orders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("BuyerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToBuy")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.PrimaryHub", b =>
                {
                    b.Property<int>("PrimaryHubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrimaryHubID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.HasKey("PrimaryHubID");

                    b.HasIndex("LocationID");

                    b.ToTable("PrimaryHubs");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarmerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("FarmerID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.RatingAndReview", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("BuyerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewID");

                    b.HasIndex("BuyerID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.SecondaryHub", b =>
                {
                    b.Property<int>("SecondaryHubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecondaryHubID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryHubID")
                        .HasColumnType("int");

                    b.HasKey("SecondaryHubID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PrimaryHubID");

                    b.ToTable("SecondaryHubs");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Transactions", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.HasKey("TransactionID");

                    b.HasIndex("OrderID")
                        .IsUnique()
                        .HasFilter("[OrderID] IS NOT NULL");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.UserMessages", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiverID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Users", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFarmer")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("AddressID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Delivery", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Location", "Locations")
                        .WithMany("Deliveries")
                        .HasForeignKey("CurrentLocationID");

                    b.HasOne("KrishiBazaarProject.Models.Orders", "Order")
                        .WithOne("Delivery")
                        .HasForeignKey("KrishiBazaarProject.Models.Delivery", "OrderID");

                    b.Navigation("Locations");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Orders", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Users", "User")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerID");

                    b.HasOne("KrishiBazaarProject.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.PrimaryHub", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Location", "Location")
                        .WithMany("PrimaryHubs")
                        .HasForeignKey("LocationID");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Product", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.HasOne("KrishiBazaarProject.Models.Users", "User")
                        .WithMany("Products")
                        .HasForeignKey("FarmerID");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.RatingAndReview", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Users", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerID");

                    b.HasOne("KrishiBazaarProject.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID");

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.SecondaryHub", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Location", "Location")
                        .WithMany("SecondaryHubs")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KrishiBazaarProject.Models.PrimaryHub", "PrimaryHub")
                        .WithMany("SecondaryHubs")
                        .HasForeignKey("PrimaryHubID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Location");

                    b.Navigation("PrimaryHub");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Transactions", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Orders", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("KrishiBazaarProject.Models.Transactions", "OrderID");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.UserMessages", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Users", "Receiver")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ReceiverID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KrishiBazaarProject.Models.Users", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Users", b =>
                {
                    b.HasOne("KrishiBazaarProject.Models.Location", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressID");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Location", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("PrimaryHubs");

                    b.Navigation("SecondaryHubs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Orders", b =>
                {
                    b.Navigation("Delivery")
                        .IsRequired();

                    b.Navigation("Transaction")
                        .IsRequired();
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.PrimaryHub", b =>
                {
                    b.Navigation("SecondaryHubs");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("KrishiBazaarProject.Models.Users", b =>
                {
                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
